# Generated by scripts/gen-formula.sh — do not edit by hand.
class Flick < Formula
  desc "Frictionless file transfer CLI. Share files with a short code."
  homepage "https://flick.d3l.tech"
  version "0.0.1"

  on_macos do
    on_arm do
      url "https://apt.d3l.tech/releases/v0.0.1/flick-darwin-arm64"
      sha256 "ab4d29019c26484f351efc524eb4158750da6d0ac677aedcfaadb9c1619af9de"

      def install
        bin.install "flick-darwin-arm64" => "flick"
      end
    end

    on_intel do
      url "https://apt.d3l.tech/releases/v0.0.1/flick-darwin-amd64"
      sha256 "8398e30a3db5e027eff47a00e782a385185cb36af17c79d9ac5945780941d315"

      def install
        bin.install "flick-darwin-amd64" => "flick"
      end
    end
  end

  test do
    system "#{bin}/flick", "--version"
  end
end
