# Generated by scripts/gen-formula.sh — do not edit by hand.
class Flick < Formula
  desc "Frictionless file transfer CLI. Share files with a short code."
  homepage "https://flick.d3l.tech"
  version "0.2.6"

  on_macos do
    on_arm do
      url "https://apt.d3l.tech/releases/v0.2.6/flick-darwin-arm64"
      sha256 "950adc5bd7fbf5b0374128b3803045498f3f5ec20043983d98a0924ae4e2b481"

      def install
        bin.install "flick-darwin-arm64" => "flick"
      end
    end

    on_intel do
      url "https://apt.d3l.tech/releases/v0.2.6/flick-darwin-amd64"
      sha256 "fcf20bf4ea1354dd4d678d64ac3f52342643d391128e43425fba88000a7485b3"

      def install
        bin.install "flick-darwin-amd64" => "flick"
      end
    end
  end

  test do
    system "#{bin}/flick", "--version"
  end
end
